name: Prebuild Android (commit native)

on:
  workflow_dispatch: {}

permissions:
  contents: write  # ← android/ 커밋/푸시를 위해 필요

jobs:
  prebuild-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # push 위해 전체 히스토리 필요할 수 있음

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund

      # npx로 expo CLI가 자동 내려받아집니다.
      - name: Expo prebuild (generate android/)
        run: npx expo prebuild --non-interactive --no-install

      - name: Commit & push android/
        run: |
          if [ -d android ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add android ios || true
            git add . || true
            if ! git diff --cached --quiet; then
              git commit -m "chore(prebuild): add native android/ (generated by expo prebuild)"
              git push
            else
              echo "No changes to commit"
            fi
          else
            echo "Android folder not generated; failing"
            exit 1
          fi
