name: Prebuild Android (commit native)

on:
  workflow_dispatch: {}

permissions:
  contents: write  # android/를 커밋하려면 꼭 필요

jobs:
  prebuild-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # push 위해 전체 히스토리 필요할 수 있음

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show versions
        run: |
          node -v
          npm -v
          npx --version || true
          npx expo --version || true

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Quick config/doctor (diagnostics)
        run: |
          npx expo config --json || true
          npx expo-doctor || true

      # expo-build-properties 같은 플러그인이 없어서 prebuild가 실패하는 경우가 많음
      - name: Ensure expo-build-properties is installed
        run: |
          npm ls expo-build-properties || npm i -S expo-build-properties@0.6.0

      # 중요: --no-install 빼고 돌린다 (누락 패키지를 expo가 자동 설치/정렬할 수 있게)
      - name: Expo prebuild (generate android/)
        env:
          EXPO_DEBUG: "1"
        run: |
          set -e
          # 안드로이드만 생성
          npx expo prebuild --platform android --non-interactive --clean --verbose 2>&1 | tee prebuild.log
          echo "---- prebuild exit code: $?"
          echo "---- repo root listing:"
          ls -la
          echo "---- android dir listing (if exists):"
          [ -d android ] && ls -la android || true

      - name: Commit & push android/
        run: |
          if [ -d android ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add android || true
            # iOS까지 같이 올리고 싶으면 아래 주석을 해제
            # git add ios || true
            if ! git diff --cached --quiet; then
              git commit -m "chore(prebuild): add native android/ (generated by expo prebuild)"
              git push
            else
              echo "No changes to commit"
            fi
          else
            echo "Android folder not generated; showing prebuild.log for debugging:"
            [ -f prebuild.log ] && tail -n 200 prebuild.log || echo "prebuild.log not found"
            exit 1
          fi
